# Generated by Django 3.1 on 2020-11-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='builder',
            name='Embed_link',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='builder',
            name='Twitter_handle',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='builder',
            name='Youtube_channel',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='builder',
            name='facebook_handle',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
