# Generated by Django 3.1 on 2020-10-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_auto_20201017_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyimages',
            name='category',
            field=models.CharField(default=False, max_length=30),
        ),
    ]
