# Generated by Django 3.1 on 2020-11-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_auto_20201106_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimages',
            name='Area_of_bedroom2',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='propertyimages',
            name='Area_of_bedroom3',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='propertyimages',
            name='Area_of_kitchen',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='propertyimages',
            name='Area_of_livingroom',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='propertyimages',
            name='Bedroom2_Image',
            field=models.ImageField(blank=True, default=False, null=True, upload_to='images1/'),
        ),
        migrations.AlterField(
            model_name='propertyimages',
            name='Bedroom3_Image',
            field=models.ImageField(blank=True, default=False, null=True, upload_to='images1/'),
        ),
        migrations.AlterField(
            model_name='propertyimages',
            name='Kitchen_Image',
            field=models.ImageField(blank=True, default=False, null=True, upload_to='images1/'),
        ),
        migrations.AlterField(
            model_name='propertyimages',
            name='LivingRoom_Image',
            field=models.ImageField(blank=True, default=False, null=True, upload_to='images1/'),
        ),
    ]
