# Generated by Django 3.1 on 2020-11-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_auto_20201107_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimages',
            name='Kitchen_Image',
            field=models.ImageField(default=False, upload_to='images1/'),
        ),
        migrations.AlterField(
            model_name='propertyimages',
            name='LivingRoom_Image',
            field=models.ImageField(default=False, upload_to='images1/'),
        ),
    ]
