# Generated by Django 3.1 on 2020-12-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20201110_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='type_house',
            field=models.CharField(choices=[('penthouse', 'penthouse'), ('villa', 'villa'), ('bungalow', 'bungalow')], default='penthouse', max_length=20),
        ),
    ]
